### ISSUE TITLE
Grav Shortcode External Caller Plugin not working?

### ISSUE THREAD

**Issue by mchendriks** [kgitthoene/grav-plugin-shortcode-external-caller#1]
If I put  [external-caller='/usr/bin/perl /usr/lib/cgi-bin/rfp/src/hello.cgi']  in my page it's displayed as text and not executed.

If I put: 
[external-caller='/usr/lib/cgi-bin/rfp/src/hello.cgi']
user:'matthieu@example.nl'
[/external-caller]

The same.
The plugins are enabled. What am I doing wrong?

Any help is appreciated.

**Comment by kgitthoene** [comment]
Have you deinstalled the dependency of shortcode-external-caller?
This is the plugin „Shortcode Core“. Without this plugin no shortcodes work at all.
